l_russian:
DEPLOYMENT_DEPLOYMENT_LABEL: "Призов і розгортання"
DIVISION_QUEUED: "$N$ дивіз."
DIVISIONS_QUEUED: "$N$ дивіз."
CONVEYOR_EQUIPMENT_NEED: "Необхідне оснащення:"
CONVEYOR_MANPOWER_NEED: "Необхідні людські ресурси: $AMOUNT|H$"
DEPLOYMENT_REQUIREMENT: "$NAME$: $AMOUNT$"
DEPLOYMENT_DIVISION_LABEL: "Дивізія"
DEPLOYMENT_PROGRESS_LABEL: "Прогрес"
DEPLOYMENT_PRIORITY_LABEL: "Пріоритет"
DEPLOYMENT_DEPLOY_LABEL: "Розгорнути"
DEPLOYMENT_TEMPLATE_ITEM_ADD: "§GКлацніть, щоби додати в чергу розгортання.§!"
DEPLOYMENT_TEMPLATE_ITEM_COPY: "§GКлацніть, щоби скопіювати шаблон у наш список.§!"
DEPLOYMENT_TEMPLATE_ITEM_EDIT: "§GКлацніть, щоби відредагувати шаблон дивізій.§!"
DEPLOYMENT_TEMPLATE_ITEM_VIEW: "§GКлацніть, щоби переглянути шаблон дивізій.§!"
DEPLOYMENT_TRAINING: "Тренування: $VALUE|%Y0$$MAXVALUE$"
DEPLOYMENT_TRAINING_MAXVALUE_DESC: "/$VALUE|%Y0$ (максимальний досвід розгортання залежить від кількості оснащення)"
DEPLOYMENT_CURRENT_LEVEL: "Поточний рівень розгортання — $NUMBER$ ($LEVEL|%Y0$)"
DEPLOYMENT_MANPOWER_DESC: "Людські ресурси: $VALUE|Y0$ (максимум: $MAX|Y0$)"
DEPLOYMENT_EXPERIENCE_DESC: "\nЯкщо тренування буде завершене, ця військова частина отримає достатньо досвіду, щоби бути розгорнутою на $NUMBER$ рівні ($MAXLEVEL|%Y0$), що дасть їй бойові модифікатори $EFFECT|+=%0$."
DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC: "\nЯкщо ця військова частина буде повністю оснащена, тренування буде завершене $DATE|Y$."
DEPLOYMENT_EQUIPMENT: "Оснащення: $VALUE|%Y0$"
DEPLOYMENT_EQUIPMENT_FULL_DESC: "$NAME$: $VALUE|G0$/$MAX|G0$"
DEPLOYMENT_EQUIPMENT_DESC: "$NAME$: $VALUE|Y0$/$MAX|Y0$"
DEPLOYMENT_DESIGNER: "Конструктор дивізій"
DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT: "        $NAME|Y$: $VALUE|Y0$"
DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL: "        $NAME|G$: $VALUE|G0$"
DEPLOYMENT_EQUIPMENT_CHANGE: "$NAME$: $VALUE$"
DEPLOYMENT_ADD_TEMPLATE: "Тренувати"
DEPLOYMENT_LINES_HIT_THE_CAP: "Ми можемо тренувати щонайбільше $CAP|*H$ людей.\nОбмежено максимумом розгорнутих людських ресурсів ($RATIO|H0%$ із $INFIELD|*H$, мінімум людей: $MINPOSSIBLE|*H$)"
DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP: "§RДосягнуто межу для цього шаблону.§!\n"
REGIMENTS_SELECTION_CANCEL: "Назад"
ONLY_ONE_TEMPLATE_LEFT: "Ви не можете видалити свій останній шаблон."
DELETE_TEMPLATE: "§RВидалити§! шаблон зі списку."
DELETE_TEMPLATE_TITLE: "Видалити шаблон"
DELETE_TEMPLATE_DESC: "Ви справді хочете видалити цей шаблон?"
DEPLOYMENT_REMOVE_DIVISION: "Скасувати дивізію"
DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT: "Неможливо §Rрозгорнути§! військову частину, в якої нема оснащення.\nЗачекайте, поки не буде отримано трохи оснащення."
DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER: "Неможливо §Rрозгорнути§! військову частину, в якої нема людських ресурсів."
DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING: "Неможливо §Rрозгорнути§! військову частину, яка не тренована на принаймні $VALUE|1H%$ (зараз $CURRENT|1R%$)."
DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES: "Неможливо §Rрозгорнути§! військову частину, яка перевищить межу спецпризначенців."
DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP: "Неможливо §Rрозгорнути§! військову частину, яка перевищить межу шаблону дивізій."
# ((+))
#DEPLOYMENT_HOW_TO_DESC:0 "Оберіть розгортання зі списку, а далі §Gклацніть§! по підсвічених провінціях на мапі для вказання точки розгортання.\n§gВійська, розгорнуті with incomplete equipment will fetch them through the reinforcement requests.\nВраховуйте, що війська, розгорнуті надто рано, не отримають належного тренування.§!"
OPERATIONS_DESC: "§YОперації§!\n§TУстановіть пріоритет надсилання оснащення на підготовку та виконання операцій.§!"
OPERATIONS_EMPTY: "§GЗапитів для операцій зараз нема.§!"
DEPLOYMENT_RAIDS_DESC: "§YНальоти§!\n§TУстановіть пріоритет надсилання оснащення на підготовку нальотів.§!"
DEPLOYMENT_RAIDS_EMPTY: "§GЗапитів для нальотів зараз нема.§!"
REINFORCEMENT: "Підкріплення"
REINFORCEMENT_DESC: "§YПідкріплення§!\n§TУстановіть пріоритет надсилання оснащення в якості підкріплень для активних військ замість черги розгортання та поліпшень.§!"
REINFORCEMENT_EMPTY: "§GЗапитів на оснащення зараз нема.§!"
UPGRADES: "Поліпшення"
UPGRADES_DESC: "§YПоліпшення§!\n§TУстановіть пріоритет надсилання оснащення для поліпшення активних військ замість черги розгортання та підкріплень.§!"
UPGRADES_EMPTY: "§GЗапитів на поліпшення зараз нема.§!"
group_infantry_title: "Піхотні батальйони"
group_mobile_title: "Мобільні батальйони"
group_armor_title: "Танкові батальйони"
group_support_title: "Роти підтримки"
group_combat_support_title: "Батальйони бойової підтримки"
group_mobile_combat_support_title: "Мобільні батальйони бойової підтримки"
group_armor_combat_support_title: "Танкові батальйони бойової підтримки"
NEW_GROUP_ADDITIONAL_COST: "Нова група $VALUE|H0$£army_experience£"
GARRISONS: "Гарнізони"
GARRISONS_DESC: "§YГарнізони§!\n§TУстановіть пріоритет надсилання оснащення гарнізонам.§!"
GARRISONS_EMPTY: "§GЗапитів для гарнізонів зараз нема.§!"
TIMED_ACTIVITY_TITLE: "$NAME$ проти: $COUNTRY$"
TIMED_ACTIVITY_ALERT_TITLE: "$NAME|H$ проти: $COUNTRY|H$"
TIMED_ACTIVITY_ENTRY_DESC: "§TУстановіть пріоритет виділення оснащення для підтримки цієї дипломатичної діяльності.§!"
TIMED_ACTIVITY_ENTRY_COMPLETE_DESC: "§GЗібрано максимальну кількість оснащення.§!"
LAND_DEPLOYMENT: "§TРозгортання військ§!"
NAVAL_DEPLOYMENT: "§TРозгортання кораблів§!"
AIR_DEPLOYMENT: "§TРозгортання літаків§!"
DIVISION_DESIGNER_RENAME: "Перейменувати"
DIVISION_DESIGNER_UPDATE: "Оновити"
DEPLOY: "Розгорнути"
EDIT: "Змінити"
VIEW: "Переглянути"
COPY: "Скопіювати"
# ((+))
#DO_NOT_CONTAINS_TEMPLATE:0 "§RНе можна видалити цей шаблон. Country does not contain this Template.§!"
HAS_ARMIES_WITH_TEMPLATE: "§RНе можна видалити цей шаблон, тому що його використовують дивізії (§H$AMOUNT$ од.§!).§!"
HAS_ARMIES_WITH_OLD_TEMPLATE: "§RНе можна видалити цей шаблон, тому що $AMOUNT|H$ дивізій переводяться з цього шаблону на новий (очікують на оснащення, потрібне для нового шаблону).§!"
HAS_EXILE_TRANSFER_WITH_TEMPLATE: "§RНе можна видалити цей шаблон, тому що його використовують дивізії, які втекли у вигнання (§H$AMOUNT$ од.§!).§!"
#HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "Не можна §Rвидалити§! цей шаблон from the country. Country has $AMOUNT|H$ deployments using this template."
HAS_GARRISON_WITH_TEMPLATE: "§RНе можна видалити цей шаблон, тому що він використовується як шаблон для гарнізонів на деяких окупованих територіях.§!"
DEPLOYMENT_TEMPLATE_LABEL: "Шаблони"
TEMPLATE_PRIO_0: "Резерв"
TEMPLATE_PRIO_0_DESC: "Військові частини з цим шаблоном отримуватимуть оснащення останніми та з найнижчим пріоритетом після свого розгортання. Ідеально для військ, що охороняють бази тощо."
TEMPLATE_PRIO_1: "Стандарт"
TEMPLATE_PRIO_1_DESC: "Військові частини з цим шаблоном отримуватимуть оснащення й поповнення з середнім пріоритетом після свого розгортання."
TEMPLATE_PRIO_2: "Еліта"
TEMPLATE_PRIO_2_DESC: "Військові частини з цим шаблоном отримуватимуть оснащення раніше за всіх і з найвищим пріоритетом після свого розгортання. Використовуйте для своїх найкращих військ і де вони найкорисніші."
DEPLOYMENT_LEND_LEASE_COUNTRY: "Ленд-ліз: $COUNTRY$"
ADD_CONVEYOR_LINE_BUTTON_LABEL: "Додати част."
ADD_CONVEYOR_LINE_BUTTON_DESC: "Додати військову частину $CONVEYOR|H$ для паралельної підготовки.\n\n§GShift + клацніть§!, щоби додати 5 частин."
CONVEYOR_GENERIC_NAME_EDIT_DESC: "Уведіть тут текст, щоби змінити стандартну назву частини."
CONVEYOR_TEMPLATE_ICON_DESC: "Ця лінія розгортання створює дивізії з шаблоном $TEMPLATE|H$."
CANCEL_CONVEYOR_TOOLTIP: "§RСкасувати§! створення всіх ліній розгортання."
DEPLOY_CONVEYOR_TOOLTIP: "§GКлацніть§!, щоби миттєво розгорнути всі лінії."
DEPLOY_CONVEYOR_DISABLED_TOOLTIP: "Немає частин, готових до §Rрозгортання§!."
CONVEYOR_CANCEL_TITLE: "§RСкасувати§! створення"
CONVEYOR_CANCEL_DESC: "Ви справді хочете §Rскасувати§! створення всіх ліній розгортання?"
CONVEYOR_LINE_CANCEL_DESC: "§RСкасувати§! створення цієї лінії."
CONVEYOR_LINE_CANCEL_ACCEPT_TITLE: "§RСкасувати§! лінію розгортання"
# ((+))
#CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "Ви справді хочете §Rскасувати§! producing this deployment line?\n(Deployment will be also §RRemoved§!)"
#CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "Ви справді хочете §Rскасувати§! producing this deployment line?"
CONVEYOR_GROUP_ASSIGN_DESC: "§GКлацніть§!, щоби прикріпити частини до наказу.\n§GКлацніть правою кнопкою§!, щоби скинути прикріплення до наказу."
#CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "Deployment should have at least one order within theater to be assigned to any group."
#CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "Deployment should have target location to be assigned to any group."
CONVEYOR_SET_LOCATION_DESC: "§GКлацніть§!, щоб установити точку розгортання для цих частин.\n§GКлацніть правою кнопкою§!, щоби скинути точку."
CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§GКлацніть§!, щоб установити точку розгортання для цих частин.\n§GКлацніть правою кнопкою§!, щоби скинути точку.\n§YЦе колоніальний шаблон і його можна розмістити тільки в країні походження!§!"
CONVEYOR_SET_LOCATION_NOT_SET: "§RТочку не вказано§!"
CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC: "Друкуйте тут, щоби змінити префікс поточної лінії."
CONVEYOR_LINE_DEPLOY_DESC: "§GКлацніть§!, щоби миттєво розмістити цю лінію."
#CONVEYOR_SERIES_INCREASE_DESC:0 "Increase the number of serial training of divisions that each line will complete.\n\nSetting to infinite means each line will train a new division when a previous one is deployed."
#CONVEYOR_SERIES_AMOUNT_DESC:0 "This is the amount of divisions that each line will train before being removed.\n\nSetting to infinite means each line will train a new division when a previous one is deployed."
#CONVEYOR_SERIES_DECREASE_DESC:0 "Decrease the number of serial training of divisions that each line will complete.\n\nSetting to infinite means each line will train a new division when a previous one is deployed."
CONVEYOR_LOW_PRIORITY_DESC: "Низький пріоритет підкріплень"
CONVEYOR_MEDIUM_PRIORITY_DESC: "Середній пріоритет підкріплень"
CONVEYOR_HIGH_PRIORITY_DESC: "Високий пріоритет підкріплень"
CONVEYOR_CAN_NOT_TRAIN: "§RНедостатньо оснащення для подальшого тренування.§!"
CONVEYOR_CAN_NOT_MANPOWER_TRAIN: "§RНедостатньо людських ресурсів для подальшого тренування.§!"
CONVEYOR_CAN_NOT_TRAIN_COUNT: "§RНедостатньо людських ресурсів або оснащення для тренування $DIVS|H$ дивізій.§!"
CONVEYOR_COLLAPSE_DESC: "§GКлацніть§!, щоби згорнути."
CONVEYOR_EXPAND_DESC: "§GКлацніть§!, щоби розгорнути."
CONVEYOR_MOVE_UP: "§GКлацніть§!, щоби перемістити вгору.\n§GShift + клацніть§!, щоби перемістити на початок."
CONVEYOR_MOVE_DOWN: "§GКлацніть§!, щоби перемістити вниз.\n§GShift + клацніть§!, щоби перемістити в кінець."
DEPLOYMENT_LOW_PRIORITY_DESC: "Низький пріоритет оснащення"
DEPLOYMENT_MEDIUM_PRIORITY_DESC: "Середній пріоритет оснащення"
DEPLOYMENT_HIGH_PRIORITY_DESC: "Високий пріоритет оснащення"
CONVEYOR_HAS_BAD_LOCATION: "Цільова локація зараз §Rнедоступна§! для розгортання."
CONVEYOR_TRAINING_NOT_FINISHED: "Тренування цієї лінії ще не завершене."
CONVEYOR_SERIES_CURRENT_AMOUNT_DESC: "Номер поточної серії розгортання в лінії."
CONVEYOR_LINE_SERIES_BASE: "$CURRENT$/$TARGET$"
DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL: "§HСтерти авторську назву.§!\nГра спробує повернути первісну назву цієї частини, якщо тільки вона не була зайнята."
DEPLOYMENT_LINE_CHOOSE_OTHER_NAME: "§HОбрати іншу історичну назву.§!\n§GКлацніть§!, щоби відкрити список усіх доступних історичних назв. Групу назв можна змінити під час редагування шаблону дивізій."
DEPLOYMENT_LINE_EDIT_NAME: "§GКлацніть§! і друкуйте тут, щоб увести авторську назву."
DEPLOYMENT_LINE_OUT_OF_NAMES: "§gІсторичні назви скінчилися.§!"
MISSING_SPECIAL_FORCES_CAP: "§RНедостатня межа сил спеціальних операцій.§!"
EXCEEDING_DIVISION_CAP: "§RПеревищення межі шаблону дивізій.§!"
TRAINING_HALTED: "Тренування було зупинене\n"
CANNOT_DELETE_SPECIAL_TEMPLATES: "Не можна видаляти спеціальні шаблони."
DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS: "Не можна тренувати нову дивізію з спеціальним шаблоном."
DEPLOYMENT_EXILE_WITH_NO_CAPITAL: "Як §Hуряд у вигнанні§! ми мусимо контролювати §Hстолицю§!, щоб тренувати нові дивізії."
CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP: "Не можна змінити цей шаблон, тому що зміни перевищать нашу межу спецпризначенців."
CANT_CHANGE_DUE_TO_DIVISION_CAP: "Не можна змінити цей шаблон, тому що зміни перевищать нашу межу дивізій."
NO_SPECIAL_FORCES: "У цьому шаблоні немає жодних сил спеціальних операцій."
SPECIAL_FORCES_IN_TEMPLATE: "Цей шаблон використовує $NUM|Y$ з дозволеної кількості сил спеціальних операцій."
SPECIAL_FORCES_CAP_DESC: "Наразі Ви втримуєте $USED|Y$ та тренуєте $IN_TRAINING|Y$ із $CAP|Y$ дозволеної кількості спецпризначенців."
DIVISION_CAP_OF_TEMPLATE: "Цей шаблон має межу в $NUM|Y$ дивізій."
DIVISION_CAP_USAGE_DESC: "Наразі у Вас розгорнуто $USED|Y$ і тренуються ще $IN_TRAINING|Y$ із $CAP|Y$ дозволених дивізій $NAME|Y$."
DIVISION_CAP_LIMIT_DESC: "Ця дивізія використовує межу шаблону, оскільки це найнижча межа." # (&)
DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE: "Це залишає місце для $TRAINABLE|Y$ дивізій із цим шаблоном."
SHOW_DECOMMISSIONED_TEMPLATES: "Показати §Hвиведені з експлуатації§!"
DECOMMISSION_TEMPLATE_TOGGLE_ON: "Вивести з експлуатації"
DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC: "§GКлацніть§!, щоб вивести цей шаблон із експлуатації, позначивши його як недійсний."
DECOMMISSION_TEMPLATE_TOGGLE_OFF: "Повернути в експлуатацію"
DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC: "§GКлацніть§!, щоби повернути цей шаблон в експлуатацію, позначивши його як дійсний."
DEPLOYMENT_VIEW_SPECIAL_FORCES_DETAILS: "$USED$/$CAP$"


DEPLOYMENT_HOW_TO_DESC:0 "Виберіть військові частини зі списку та §Gклацніть§! по виділених провінціях, щоби розгорнути їх.\n§gВійськові частини, не до кінця укомплектовані оснащенням, отримають її крізь запити на поповнення.\nЧастини, розгорнуті раніше належного, не пройшли належну підготовку.§!"
DO_NOT_CONTAINS_TEMPLATE:0 "§RЦей шаблон неможливо видалити. У країни немає цього шаблону.§!"
HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "Цей шаблон неможливо §Rприбрати§! в цієї країни. В цій державі розгорнуті частини, що використовують його ($AMOUNT|H$)."
CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "Ви справді хочете §Rскасувати§! створення цієї лінії розгортання?\n(Розгортання також буде §Rвидалене§!)"
CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "Ви справді хочете §Rскасувати§! створення цієї лінії розгортання?"
CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "У частин мусить бути принаймні один наказ на театр воєнних дій, закріплений за будь-якою групою."
CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "У частин мусить бути точка розгортання, закріплена за будь-якою групою."
CONVEYOR_SERIES_INCREASE_DESC:0 "Збільшує кількість дивізій, котрі пройдуть навчання на цій лінії перед розгортанням.\n\nЯкщо вибрано параметр «нескінченність», то навчання наступної дивізії почнеться одразу після розгортання попередньої."
CONVEYOR_SERIES_AMOUNT_DESC:0 "Кількість дивізій, які пройдуть навчання на цій лінії перед розгортанням.\n\nЯкщо вибрано параметр «нескінченність», то навчання наступної дивізії почнеться одразу після розгортання попередньої."
CONVEYOR_SERIES_DECREASE_DESC:0 "Зменшує кількість дивізій, які пройдуть навчання на цій лінії перед розгортанням.\n\nЯкщо вибрано параметр «нескінченність», то навчання наступної дивізії почнеться одразу після розгортання попередньої."
